# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         RayApp
version:      1.145
version_from: lib/RayApp.pm
installdirs:  site
requires:
    CGI:                           0
    Test::More:                    0
    XML::LibXML:                   0
    XML::LibXSLT:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
